version: "3.7"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      TZ: "Europe/Zurich"